---
title: "Traffic_Camera_Offences_Fines_Markdown"
output: html_document
date: '2022-07-28'
runtime: shiny

  
  
---


```{r} 
library(tidyverse)
library(ggplot2)
library(shiny)
library(ozmaps)
library(sf)
library(janitor)
library(basemaps)
library(tmap)
```


```{r}

df <- read_csv("Traffic_camera_offences_and_fines.csv")

df_map <- read_csv("Traffic_Camera_Locations_-_Point_Map.csv")

df_new <- df_map %>%
janitor::clean_names() %>%
	mutate(location = str_remove(location,"\\(")) %>%
	mutate(location = str_remove(location,"\\)")) %>% 
	separate(location,into=c('lat','long'),sep=',')


```


```{r}

plot <- ggplot(df,aes(x = Clt_Catg, y = Sum_Pen_Amt)) + 
  geom_col()

plot

 
```



```{r}

#install spatial packages

#load spatial packages
library(plyr)
library(dplyr)
library(ggplot2)
library(rgdal)
library(tmap)
library(ggmap)
library(dplyr)
library(sf)
library(ggspatial)
library(rlang)
library(broom)
library(tidyverse)
library(readxl)
library(raustats)
library(purrr)
library("Census2016")
```
```{r}
df_new$lat <- as.numeric(df_new$lat)
df_new$long <- as.numeric(df_new$long)

```

```{r}

myLocation <- c(149.103,-35.45,149.25,-35.192)

myMap <- get_map(location = myLocation, source = "osm", maptype = "watercolor", crop = FALSE)
ggmap(myMap) + geom_point(data = df_new, aes(x = long, y = lat),
 alpha = .5, color="darkred", size = 3)

```

