---
title: "Traffic_Camera_Offences_Fines_Markdown"
output: html_document
date: '2022-07-28'
runtime: shiny

  
  
---


```{r} 
library(tidyverse)
library(ggplot2)
library(shiny)
```


```{r}

df <- read_csv("Traffic_camera_offences_and_fines.csv")
```


```{r}

plot <- ggplot(df,aes(x = Clt_Catg, y = Sum_Pen_Amt)) + 
  geom_col()

plot

 
```

```{r, echo=FALSE}
shinyApp(

  ui = fluidPage(
       titlePanel("Traffic Camera Offence and Fines"),
    sidebarLayout(
      sidebarPanel(
selectInput("var",
            label = "Choose X Axis", 
            choices = list("State of Vehicle Registration", "Vehicle Category","Camera Type"), 
            selected = "Camera Type")
),
mainPanel(
  plotOutput("plot")
)
)
  ),

  server = function(input, output) {
    
df <- read_csv("Traffic_camera_offences_and_fines.csv")

  
  output$plot <- renderPlot({ggplot(df,aes(x = switch(input$var,"State of Vehicle Registration" = Rego_State, "Vehicle Category" = Clt_Catg, "Camera Type" = Camera_Type),
                                             y = Sum_Pen_Amt)) +
                                      geom_col()
                                    
  })
  },

  options = list(height = 500)
)



```